# Generated by Django 4.2.14 on 2024-08-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0004_task_created_by_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
